name: Update site

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install requests
      - name: Get site
        run: |
          python scraper.py
      - name: Login
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add .
          git commit -m "update site"
          git push origin main